#!/bin/sh
# Generate the FICTIONAL "Benefits Notices" sandbox workspace under reference/sandbox/.
#
# The sandbox is a fully populated, safe-to-share example a PM can open in their harness
# to trial the setup. It is GENERATED (not hand-curated) so it doubles as a regression
# test of the templates/scripts and never drifts. Re-run after any template change.
#
# Usage: ./seed-sandbox.sh
#
# All content is fictional. No real client, program, system, repo, or person.

set -eu

unset CDPATH || true
kit_dir=$(cd -- "$(dirname -- "$0")/.." && pwd)
ref="$kit_dir/reference"
ws="$ref/sandbox"

# Fresh regenerate.
rm -rf "$ws"
"$kit_dir/scripts/new-workspace.sh" --name "sandbox" --dir "$ref" --with-support >/dev/null

# Fixed date keeps regeneration deterministic (no churn on every run).
D="2026-07-22"
support="$ws/agentic-support"
cf="$support/context-fabric"

# ---- Root README (sandbox intro + FICTIONAL banner) -------------------------
cat > "$ws/README.md" <<'EOF'
# Benefits Notices Workspace (SANDBOX)

> **FICTIONAL SANDBOX.** Every product, system, repository, and person here is made up.
> This exists so a PM can open a real, populated workspace and trial the kit before
> standing up their own. It is generated by `scripts/seed-sandbox.sh`; do not hand-edit.

"Benefits Notices" (BN) is a fictional product team that designs and ships outbound
beneficiary notices (eligibility determinations, appeal rights, renewals).

## Trial it in ~5 minutes

1. Open this folder in your agent tool (Claude Code reads `CLAUDE.md`; Codex/OpenCode/Cursor read `AGENTS.md`).
2. Ask your agent: "Read the root AGENTS.md and tell me the boundaries and vocabulary for this workspace."
3. Look at `product-work/benefits-notices/AGENTS.md` — note the one-line Context Fabric profile declaration.
4. Open `agentic-support/context-fabric/records/profiles/benefits-notices.json` — the shared facts an agent resolves.
5. Read the skill at `agentic-support/skills/notice-change-brief/SKILL.md`, then ask your agent to run it.
6. From this folder, run the kit's validator: `../../scripts/validate-workspace.sh .`

## Layout

- `product-work/benefits-notices/` — the (fictional) product area, declaring its Context Fabric profile.
- `prototyping/` — empty; where spikes would go.
- `agentic-support/` — one skill (`notice-change-brief`) and a small Context Fabric (one system, two repos, one profile).
- `docs/` — suggested lanes, with one sample plan and one sample solution.
EOF

# ---- Root AGENTS.md (thin, with FICTIONAL banner) ---------------------------
cat > "$ws/AGENTS.md" <<'EOF'
# Benefits Notices Workspace (SANDBOX) -- Agent Instructions

<!-- FICTIONAL SANDBOX generated by scripts/seed-sandbox.sh. All content is made up. -->

Scope: Shared product workspace for the fictional Benefits Notices (BN) team. Example only.

## Boundaries

- Product docs, research, and deliverables for BN live here.
- No code checkouts, credentials, or client-identifying data in this workspace.
- Client-sensitive material would need review before sharing outside the team.
- Nearest, most-specific `AGENTS.md` wins for local decisions, unless it conflicts with this boundary.

## Layout

- `product-work/` — shared product work the team relies on. One folder per product area; each declares one Context Fabric profile.
- `prototyping/` — spikes, mockups, experiments. No assigned profile.
- `agentic-support/` — reusable skills and shared context (Context Fabric).

## Where things live

- Reusable procedures: `agentic-support/skills/<name>/SKILL.md`. Do not duplicate them in product folders.
- Shared facts (systems, repos, profiles): resolve the product's `product:<slug>` profile in the Context Fabric.

## Vocabulary

- "notice" = an outbound beneficiary communication (determination, appeal rights, renewal).
- "template set" = the versioned collection of notice layouts.
- Notice IDs: BN-001 through BN-140 (stable identifiers).
EOF
printf '@AGENTS.md\n' > "$ws/CLAUDE.md"

# ---- Product area: product-work/benefits-notices/ ---------------------------
pa="$ws/product-work/benefits-notices"
mkdir -p "$pa/docs/solutions" "$pa/docs/plans"
cat > "$pa/AGENTS.md" <<'EOF'
# Benefits Notices -- Agent Instructions

Context Fabric profile: product:benefits-notices

Steward: Priya Anand (fictional)

## Boundaries

- Covers the content, layout, and delivery logic of BN notices. Does not cover eligibility rules (those live upstream).
- This is a strategy/documentation workspace, not a software codebase.

## Where things live

- Reusable procedures: the support layer's `skills/`.
- Shared facts about BN's systems and repos: resolve `product:benefits-notices` in the Context Fabric.
- Synthesis and deliverables: this area's `docs/` lanes.

## Local conventions

- Notice IDs BN-001..BN-140 are stable; never renumber.
EOF
printf '@AGENTS.md\n' > "$pa/CLAUDE.md"

cat > "$pa/docs/plans/renewal-notice-refresh.md" <<EOF
---
purpose: Plan to refresh the renewal notice (BN-072) for plain-language compliance.
audience: BN team and reviewers.
status: Draft.
last_updated: $D
---

# Plan: Renewal Notice (BN-072) Plain-Language Refresh

Fictional example plan. Shows what belongs in a \`docs/plans/\` lane.

## Goal
Rewrite BN-072 to pass a plain-language review without changing the underlying determination logic.

## Steps
1. Pull the current BN-072 template set and the last three months of support tickets referencing it.
2. Draft the rewrite; run the \`notice-change-brief\` skill to produce the change brief.
3. Expert-panel review (plain-language, accessibility, policy-accuracy lenses).
4. Ship to the template set; log the change.
EOF

cat > "$pa/docs/solutions/notice-id-stability.md" <<EOF
---
purpose: Why notice IDs are stable identifiers and how to add a new one.
audience: BN team.
status: Active.
last_updated: $D
---

# Solution: Keep Notice IDs Stable

Fictional example solution note. Shows what belongs in a \`docs/solutions/\` lane.

Notice IDs (BN-001..BN-140) are referenced by the notice service, analytics, and support macros.
Renumbering breaks all three. To add a notice, allocate the next unused BN-### and record it here;
never reuse or renumber an existing ID.
EOF

# ---- Context Fabric records -------------------------------------------------
cat > "$cf/records/systems/eligibility-platform.json" <<EOF
{
  "kind": "systemResource",
  "id": "system:eligibility-platform",
  "schemaVersion": "1.0.0",
  "updatedAt": "${D}T00:00:00Z",
  "name": "Eligibility Platform (fictional)",
  "description": "Upstream system that emits beneficiary eligibility determinations BN reacts to.",
  "interfaces": [
    { "type": "api", "url": "https://eligibility.example.gov/api" }
  ],
  "provenance": { "source": "sandbox seed", "addedBy": "kit" },
  "validation": { "validatedBy": "kit", "validatedAt": "${D}T00:00:00Z" }
}
EOF
cat > "$cf/records/systems/notices-tracker.json" <<EOF
{
  "kind": "systemResource",
  "id": "system:notices-tracker",
  "schemaVersion": "1.0.0",
  "updatedAt": "${D}T00:00:00Z",
  "name": "Notices Tracker (fictional Jira)",
  "description": "Work tracker where BN issues live.",
  "interfaces": [
    { "type": "issue-tracker", "url": "https://tracker.example.gov/projects/BN" }
  ],
  "provenance": { "source": "sandbox seed", "addedBy": "kit" },
  "validation": { "validatedBy": "kit", "validatedAt": "${D}T00:00:00Z" }
}
EOF
cat > "$cf/records/resources/bn-notice-service.json" <<EOF
{
  "kind": "repositoryResource",
  "id": "repository:example-gov/bn-notice-service",
  "schemaVersion": "1.0.0",
  "updatedAt": "${D}T00:00:00Z",
  "system": "system:notices-tracker",
  "url": "https://git.example.gov/example-gov/bn-notice-service",
  "lifecycle": "active",
  "accessState": "accessible",
  "syncable": true,
  "provenance": { "source": "sandbox seed", "addedBy": "kit" },
  "validation": { "validatedBy": "kit", "validatedAt": "${D}T00:00:00Z" }
}
EOF
cat > "$cf/records/resources/eligibility-events.json" <<EOF
{
  "kind": "repositoryResource",
  "id": "repository:example-gov/eligibility-events",
  "schemaVersion": "1.0.0",
  "updatedAt": "${D}T00:00:00Z",
  "system": "system:eligibility-platform",
  "url": "https://git.example.gov/example-gov/eligibility-events",
  "lifecycle": "active",
  "accessState": "accessible",
  "syncable": true,
  "provenance": { "source": "sandbox seed", "addedBy": "kit" },
  "validation": { "validatedBy": "kit", "validatedAt": "${D}T00:00:00Z" }
}
EOF
cat > "$cf/records/profiles/benefits-notices.json" <<EOF
{
  "kind": "productProfile",
  "id": "product:benefits-notices",
  "schemaVersion": "1.0.0",
  "updatedAt": "${D}T00:00:00Z",
  "name": "Benefits Notices",
  "description": "Designs and ships outbound beneficiary notices.",
  "aliases": ["bn", "notices"],
  "maintainers": [ { "name": "Priya Anand (fictional)", "role": "product steward" } ],
  "systems": [
    { "systemId": "system:notices-tracker", "anchors": [ { "type": "jira-project", "value": "BN" } ] },
    { "systemId": "system:eligibility-platform", "anchors": [] }
  ],
  "repositories": [
    {
      "resourceId": "repository:example-gov/bn-notice-service",
      "alias": "notice-service",
      "selectionTier": "primary",
      "coverage": "direct",
      "useWhen": "Any task about notice content, layout, or delivery logic."
    },
    {
      "resourceId": "repository:example-gov/eligibility-events",
      "alias": "eligibility-contract",
      "selectionTier": "supporting",
      "coverage": "reference",
      "useWhen": "When a notice depends on the shape of an upstream determination event."
    }
  ],
  "taskGuidance": {
    "synthesisBelongsIn": "product-work/benefits-notices/docs",
    "notes": "Deliverables and research for BN go under the product area's docs lanes."
  },
  "provenance": { "source": "sandbox seed", "addedBy": "kit" },
  "validation": { "validatedBy": "kit", "validatedAt": "${D}T00:00:00Z" }
}
EOF

# ---- Skill: replace example-skill with notice-change-brief ------------------
skills="$support/skills"
rm -rf "$skills/example-skill"
mkdir -p "$skills/notice-change-brief"
cat > "$skills/notice-change-brief/SKILL.md" <<'EOF'
---
workflow_id: notice-change-brief
version: 1
status: enabled
owner: Benefits Notices
source_of_truth: true
portable_across_harnesses: true
description: Draft a change brief for a proposed edit to a beneficiary notice, grounded in the BN product context.
argument-hint: "[notice ID, e.g. BN-072, and the proposed change]"
---

# Notice Change Brief

Use this skill when someone proposes changing the content or layout of a BN notice and needs a
reviewable brief before the change ships.

## Required Context
1. The workspace root `AGENTS.md`.
2. `product-work/benefits-notices/AGENTS.md` and the `product:benefits-notices` profile.
3. The current template set for the affected notice ID.

## Procedure
1. Confirm the notice ID (BN-###) and summarize the proposed change in one sentence.
2. Identify who is affected and any upstream dependency (check the profile's `eligibility-contract` repo).
3. Draft the brief: what changes, why, plain-language impact, accessibility impact, and rollback.
4. Save it to `product-work/benefits-notices/docs/plans/`.

## Guardrails
- Never invent determination logic; notices reflect upstream rules, they do not set them.
- No credentials, no client-identifying data.

## Output Shape
A markdown brief with: Summary, Affected notices, Upstream dependency, Change detail, Plain-language impact, Accessibility impact, Rollback.

## Harness Interpretation
Claude, Codex, OpenCode, and other harnesses produce the same brief shape. This file is the source of truth for the procedure.
EOF

cat > "$skills/skill-manifest.yaml" <<'EOF'
schema_version: 1

# skills/<name>/ is the source of truth. Runtime copies are generated by sync-skills.sh.
source_of_truth: skills

skills:
  - name: notice-change-brief
    version: 1.0.0
    status: enabled

targets:
  opencode: ~/.config/opencode/skills
  codex: ~/.agents/skills
  claude: ~/.claude/skills
EOF

printf 'Seeded sandbox at: %s\n' "$ws"
