#!/bin/sh
# Generate the FICTIONAL "Benefits Notices" sandbox workspace under reference/sandbox/.
#
# The sandbox is a fully populated, safe-to-share example a team can open in their harness
# to trial the setup. It is GENERATED (not hand-curated) so it doubles as a regression
# test of the templates and the support engine, and never drifts. Re-run after any
# template change; CI fails if the regenerated tree differs from the committed one.
#
# Usage: ./seed-sandbox.sh
#
# All content is fictional. No real client, program, system, repository, or person.

set -eu

unset CDPATH || true
kit_dir=$(cd -- "$(dirname -- "$0")/.." && pwd)
ref="$kit_dir/reference"
ws="$ref/sandbox"

# Fresh regenerate.
rm -rf "$ws"
"$kit_dir/scripts/new-workspace.sh" --name "sandbox" --dir "$ref" --with-support >/dev/null

# Fixed date keeps regeneration deterministic (no churn on every run).
D="2026-07-29"
support="$ws/agentic-support"
cf="$support/context-fabric"

# ---- Root README (sandbox intro + FICTIONAL banner) -------------------------
cat > "$ws/README.md" <<'EOF'
# Benefits Notices Workspace (SANDBOX)

> **FICTIONAL SANDBOX.** Every product, system, repository, and person here is made up.
> This exists so you can open a real, populated workspace and trial the kit before
> standing up your own. It is generated by `scripts/seed-sandbox.sh`; do not hand-edit.

"Benefits Notices" (BN) is a fictional product team that designs and ships outbound
beneficiary notices (eligibility determinations, appeal rights, renewals).

## Trial it in ~5 minutes

1. Open this folder in your agent tool (Codex/OpenCode/Cursor read `AGENTS.md`; Claude Code reads `CLAUDE.md`).
2. Ask your agent: "Read the root AGENTS.md and tell me the boundaries, the source ladder, and the vocabulary for this workspace."
3. Run the session-start probe: `./agentic-support/tools/workspace-doctor.sh`. With no
   declaration on your machine it exits 3 and tells you to run the `workspace-setup`
   skill — that fail-closed behavior *is* the feature. Ask your agent to run that skill
   and watch it interview you.
4. Ask "where does a delivery plan for the renewal notice go?" — the answer comes from
   `./agentic-support/tools/route-artifact.sh --type plan --area benefits-notices`,
   including the area's registered exception.
5. Ask "what does the notice-service repo do?" — the answer comes from a generated digest
   at `agentic-support/context-fabric/records/generated/repo-digests/`, with no git and no
   checkout.
6. Open `agentic-support/context-fabric/records/profiles/benefits-notices.json` — the
   shared facts an agent resolves from one line in a product-area `AGENTS.md`.
7. Read `agentic-support/skills/notice-change-brief/SKILL.md`, then ask your agent to run it.
8. Run the gate: `./agentic-support/validation/check-workspace.sh`.

## Layout

- `product-work/benefits-notices/` — the (fictional) product area, declaring its Context Fabric profile.
- `product-work/area-manifest.yaml` — the area registry, with one typed routing exception.
- `prototyping/` — empty; where spikes would go.
- `agentic-support/` — the support engine, plus one team skill, a small Context Fabric, and the two files a team authors itself.
- `docs/` — suggested lanes, with one sample plan and one sample solution.

## What a team authors vs. what installs verbatim

Everything under `agentic-support/` came from the kit unchanged **except** two files,
which are filled in here as examples of what your team writes:

- `agentic-support/CONCEPTS.md` — the workspace vocabulary.
- `agentic-support/docs/context-source-ladder.md` — which source to consult first.
EOF

# ---- Root AGENTS.md (thin, with FICTIONAL banner) ---------------------------
cat > "$ws/AGENTS.md" <<'EOF'
# Benefits Notices Workspace (SANDBOX) -- Agent Instructions

<!-- FICTIONAL SANDBOX generated by scripts/seed-sandbox.sh. All content is made up. -->

Scope: Shared product workspace for the fictional Benefits Notices (BN) team. Example only.

**This is one root of a multi-root workspace** — sessions normally also see a machine-local
repo-checkouts root and one or more working-materials roots. Run
`agentic-support/tools/workspace-doctor.sh` at session start; root roles are in
`agentic-support/docs/workspace-routing.md`.

## Boundaries

- Product docs, research, and deliverables for BN live here.
- No code checkouts, credentials, tokens, or client-identifying data in this tree.
- Never store member-specific harness state here (`settings.local.json`, `*.code-workspace`);
  keep it in user scope, and launch sessions from a machine-local primary folder.
- Client-sensitive material needs review before sharing outside the team.
- Nearest, most-specific `AGENTS.md` wins locally, unless it conflicts with this boundary.

## Layout

- `product-work/` — shared work the team relies on. One folder per area; each declares one profile. `area-manifest.yaml` registers areas and exceptions.
- `prototyping/` — spikes, mockups, experiments. No assigned profile.
- `agentic-support/` — the support engine: skills, Context Fabric, tools, validation.

## Which source to consult first

| Question | Consult first | If unavailable |
|---|---|---|
| Where does this artifact go? | `agentic-support/tools/route-artifact.sh` | the `artifact-routing` skill |
| What does repo X do? | `agentic-support/context-fabric/records/generated/repo-digests/` | the hydrated checkout |
| What does a notice currently say? | the template set for that notice ID | ask the BN steward |
| Does a notice depend on upstream event shape? | `repository:example-gov/eligibility-events` (reference coverage) | ask the Eligibility Platform owner |

Full ladder: `agentic-support/docs/context-source-ladder.md`.

## Vocabulary

"Notice", "template set", and the BN-### ID scheme are defined in `agentic-support/CONCEPTS.md`. Do not guess at them.
EOF
printf '@AGENTS.md\n' > "$ws/CLAUDE.md"

# ---- The two team-authored engine files -------------------------------------
cat > "$support/CONCEPTS.md" <<'EOF'
# Concepts

Shared vocabulary for the fictional Benefits Notices workspace. One of the two files a
team authors itself; everything else in this tree installed verbatim from the kit.

Glossary only — a few sentences per entry, because this file loads in every session.
Detail goes in `docs/solutions/` or a Context Fabric record.

## Benefits Notices domain

### Notice
An outbound beneficiary communication: an eligibility determination, a statement of
appeal rights, or a renewal reminder. A notice reflects upstream rules; it never sets
them.

### Template Set
The versioned collection of layouts a notice renders through. A content change and a
template-set change are different reviews with different risk.

### Notice ID
A stable identifier, BN-001 through BN-140. Referenced by the notice service, analytics,
and support macros, so renumbering breaks all three. Allocate the next unused number;
never reuse or renumber. See
`product-work/benefits-notices/docs/solutions/notice-id-stability.md`.

### Determination Event
The upstream message from the Eligibility Platform that triggers a notice. BN consumes
its shape and has no say in its contents — which is why the events repository is
`reference` coverage, not `direct`.

## Workspace pattern

The workspace-pattern vocabulary (Multi-Root Workspace, Primary Folder, Launch Shape,
Workspace Descriptor, Binding Token, Workspace Doctor, Capability Tier, Repo Digest)
ships with the engine and is preserved above this section in a real workspace. It is
elided here to keep the sandbox readable — see
`templates/support/CONCEPTS.md.template` in the kit for the full seeded set.
EOF

cat > "$support/docs/context-source-ladder.md" <<'EOF'
---
purpose: Which source to consult first for a given question in the BN workspace.
audience: Every agent session; maintained by the BN steward.
status: Active (fictional example).
---

# Context-source ladder

One of the two files a team authors itself. The compact version lives in the workspace
root `AGENTS.md`; this page carries the reasoning and the degraded paths.

A **primary**, a **declared alternate**, and a **reserve discipline**. Improvised
fallbacks — broad scans, neighboring checkouts, unscoped searches — are what turn a cheap
question into an expensive session, so every branch names its alternate up front.

## The ladder

| Question class | Primary | Declared alternate |
|---|---|---|
| Repo purpose or layout | Repo digests (`context-fabric/records/generated/repo-digests/`) | Hydrated checkout under `${AGENTIC_REPO_CHECKOUT_ROOT}/` |
| Code-level detail (rendering, delivery logic) | Hydrated checkout, hydrated via the reviewed sync manifest | Digest for orientation, plus an explicit note that checkout inspection is needed |
| Which system owns a fact, and how to reach it | Context Fabric `records/systems/` | Ask the named system owner |
| Current notice content | The template set for that notice ID | Ask the BN steward; do not reconstruct notice text from memory |
| Upstream determination event shape | `repository:example-gov/eligibility-events` (reference coverage) | Ask the Eligibility Platform owner |
| BN decision history | `product-work/benefits-notices/docs/` lanes | Ask the BN steward |
| Open BN work items | The Notices Tracker, only when the doctor reports the credential loaded | Ask the user to paste the item; never guess at ticket contents |
| External / current-events context | Web search with citations | — |

## Reserve discipline (token budget)

- Load the specific record, digest, or file section that answers the question — never a
  whole bundle, catalog, or repository tree.
- Prefer generated summaries over raw sources for orientation-level questions; drop to
  raw sources only for detail the summary cannot carry.
- Inspect before reading in full: listings, manifests, and frontmatter first.
- A source past its `do_not_rely_after` date is **unavailable**: use the declared
  alternate and say why.

## Maintenance

Add a row when a source class appears or retires, and update the compact copy in the root
`AGENTS.md` in the same change. The two must not drift.
EOF

# ---- Product area: product-work/benefits-notices/ ---------------------------
pa="$ws/product-work/benefits-notices"
mkdir -p "$pa/docs/solutions" "$pa/docs/plans" "$pa/docs/ideation" "$pa/docs/references"
cat > "$pa/AGENTS.md" <<'EOF'
# Benefits Notices -- Agent Instructions

Context Fabric profile: product:benefits-notices

Steward: Priya Anand (fictional)

## Boundaries

- Covers the content, layout, and delivery logic of BN notices. Does not cover eligibility rules — those live upstream in the Eligibility Platform.
- This is a strategy and documentation area, not a software codebase. Code lives in the machine-local checkouts root.

## Where things live

- Reusable procedures: `agentic-support/skills/`. Do not duplicate them here.
- Shared facts about BN's systems and repositories: resolve `product:benefits-notices`.
- Route outputs with `agentic-support/tools/route-artifact.sh --type <type> --area benefits-notices`. This area has a registered variance — the tool prints it.

## Local conventions

- Notice IDs BN-001..BN-140 are stable; never renumber. See `agentic-support/CONCEPTS.md`.
EOF
printf '@AGENTS.md\n' > "$pa/CLAUDE.md"

cat > "$ws/product-work/area-manifest.yaml" <<'EOF'
# Product-area registry (FICTIONAL SANDBOX).
#
# `agentic-support/tools/route-artifact.sh` reads this file, so an unregistered area gets
# a "stop and ask" instead of a guess. Exceptions are typed and carry a rationale, so an
# exception cannot outlive the situation that justified it.

areas:
  - id: benefits-notices
    profile: product:benefits-notices
    steward: Priya Anand (fictional)
    exceptions:
      - type: variance
        lanes: [docs/plans]
        rationale: Notice changes ship to real beneficiaries, so ideas graduate straight to a reviewed plan rather than resting in the ideation lane.
EOF

cat > "$pa/docs/plans/renewal-notice-refresh.md" <<EOF
---
purpose: Plan to refresh the renewal notice (BN-072) for plain-language compliance.
audience: BN team and reviewers.
status: Draft.
last_updated: $D
---

# Plan: Renewal Notice (BN-072) Plain-Language Refresh

Fictional example plan. Shows what belongs in a \`docs/plans/\` lane.

## Goal
Rewrite BN-072 to pass a plain-language review without changing the underlying determination logic.

## Steps
1. Pull the current BN-072 template set and the last three months of support tickets referencing it.
2. Draft the rewrite; run the \`notice-change-brief\` skill to produce the change brief.
3. Review through the plain-language, accessibility, and policy-accuracy lenses.
4. Ship to the template set; log the change.
EOF

cat > "$pa/docs/solutions/notice-id-stability.md" <<EOF
---
title: Notice IDs are stable identifiers; never renumber
category: conventions
problem_type: convention
applies_when:
  - adding a new notice
  - tempted to renumber or reuse a retired notice ID
tags: [notice-id, stable-identifiers, analytics]
last_updated: $D
---

# Notice IDs are stable identifiers; never renumber

Fictional example learning. Shows what belongs in a \`docs/solutions/\` lane.

## Context
Notice IDs (BN-001..BN-140) are referenced by the notice service, the analytics pipeline,
and support macros. None of the three learns about a renumber.

## Guidance
To add a notice, allocate the next unused BN-### and record it. Never reuse a retired ID
and never renumber an existing one.

## Why this matters
The ID is a contract across three systems owned by three different teams. A renumber is
cheap in the template set and expensive everywhere it is read.
EOF

# ---- Context Fabric records -------------------------------------------------
mkdir -p "$cf/records/resources/repositories/example-gov"
cat > "$cf/records/systems/eligibility-platform.json" <<EOF
{
  "kind": "systemResource",
  "id": "system:eligibility-platform",
  "schemaVersion": "1.0.0",
  "updatedAt": "$D",
  "contentLocations": [{ "path": "records/systems/eligibility-platform.json" }],
  "name": "Eligibility Platform (fictional)",
  "description": "Upstream system that emits beneficiary eligibility determinations BN reacts to.",
  "ownership": { "owner": "Eligibility Platform team (fictional)", "contact": "#eligibility-platform" },
  "interfaces": [
    {
      "type": "api",
      "url": "https://eligibility.example.gov/api",
      "accessGuidance": "Request read scope through the platform team's intake. Never store the token.",
      "validationStatus": "validated"
    }
  ],
  "provenance": { "source": "sandbox seed", "addedBy": "kit" },
  "validation": { "status": "validated", "validatedBy": "kit", "validatedAt": "$D" }
}
EOF
cat > "$cf/records/systems/notices-tracker.json" <<EOF
{
  "kind": "systemResource",
  "id": "system:notices-tracker",
  "schemaVersion": "1.0.0",
  "updatedAt": "$D",
  "contentLocations": [{ "path": "records/systems/notices-tracker.json" }],
  "name": "Notices Tracker (fictional)",
  "description": "Work tracker where BN issues live.",
  "ownership": { "owner": "BN team (fictional)", "contact": "#benefits-notices" },
  "interfaces": [
    {
      "type": "issue-tracker",
      "url": "https://tracker.example.gov/projects/BN",
      "accessGuidance": "Team membership grants read access. Token loaded per session only.",
      "validationStatus": "validated"
    }
  ],
  "provenance": { "source": "sandbox seed", "addedBy": "kit" },
  "validation": { "status": "validated", "validatedBy": "kit", "validatedAt": "$D" }
}
EOF
cat > "$cf/records/resources/repositories/example-gov/bn-notice-service.json" <<EOF
{
  "kind": "repositoryResource",
  "id": "repository:example-gov/bn-notice-service",
  "schemaVersion": "1.0.0",
  "updatedAt": "$D",
  "contentLocations": [{ "path": "records/resources/repositories/example-gov/bn-notice-service.json" }],
  "organization": "example-gov",
  "repository": "bn-notice-service",
  "system": "system:notices-tracker",
  "url": "https://git.example.gov/example-gov/bn-notice-service",
  "description": "Renders and delivers beneficiary notices from determination events.",
  "checkoutDirectory": "bn-notice-service",
  "lifecycle": "active",
  "accessState": "available",
  "syncable": true,
  "stewardship": { "owner": "BN engineering (fictional)" },
  "provenance": { "source": "sandbox seed", "addedBy": "kit" },
  "validation": { "status": "validated", "validatedBy": "kit", "validatedAt": "$D" }
}
EOF
cat > "$cf/records/resources/repositories/example-gov/eligibility-events.json" <<EOF
{
  "kind": "repositoryResource",
  "id": "repository:example-gov/eligibility-events",
  "schemaVersion": "1.0.0",
  "updatedAt": "$D",
  "contentLocations": [{ "path": "records/resources/repositories/example-gov/eligibility-events.json" }],
  "organization": "example-gov",
  "repository": "eligibility-events",
  "system": "system:eligibility-platform",
  "url": "https://git.example.gov/example-gov/eligibility-events",
  "description": "Schema definitions for upstream determination events. Read-only to BN.",
  "checkoutDirectory": "eligibility-events",
  "lifecycle": "active",
  "accessState": "available",
  "syncable": true,
  "stewardship": { "owner": "Eligibility Platform team (fictional)", "note": "BN consumes the contract; changes are theirs to make." },
  "provenance": { "source": "sandbox seed", "addedBy": "kit" },
  "validation": { "status": "validated", "validatedBy": "kit", "validatedAt": "$D" }
}
EOF
mkdir -p "$cf/records/resources/local"
cat > "$cf/records/resources/local/plain-language-standard.json" <<EOF
{
  "kind": "localReferenceResource",
  "id": "reference:plain-language-standard",
  "schemaVersion": "1.0.0",
  "updatedAt": "$D",
  "contentLocations": [{ "path": "records/resources/local/plain-language-standard.json" }],
  "name": "Plain-Language Standard (fictional)",
  "description": "The governed writing standard every outbound notice is reviewed against.",
  "location": "\${AGENTIC_WORKING_MATERIALS_ROOT_1}/standards/plain-language",
  "consultationUse": "Whether a proposed notice wording meets the organization's plain-language bar.",
  "relianceCheck": "Each rule carries a review date in the standard's own registry. A rule past its review date is treated as unavailable.",
  "provenance": { "source": "sandbox seed", "addedBy": "kit" },
  "validation": { "status": "validated", "validatedBy": "kit", "validatedAt": "$D" }
}
EOF
cat > "$cf/records/profiles/benefits-notices.json" <<EOF
{
  "kind": "productProfile",
  "id": "product:benefits-notices",
  "schemaVersion": "1.0.0",
  "updatedAt": "$D",
  "contentLocations": [{ "path": "records/profiles/benefits-notices.json" }],
  "name": "Benefits Notices",
  "description": "Designs and ships outbound beneficiary notices.",
  "aliases": ["bn", "notices"],
  "maintainers": [{ "name": "Priya Anand (fictional)", "role": "product steward" }],
  "systems": [
    {
      "systemId": "system:notices-tracker",
      "useWhen": "Looking up open BN work items or their history.",
      "anchors": [{ "type": "tracker-project", "value": "BN" }]
    },
    {
      "systemId": "system:eligibility-platform",
      "useWhen": "A notice depends on the shape or timing of an upstream determination."
    }
  ],
  "repositories": [
    {
      "resourceId": "repository:example-gov/bn-notice-service",
      "alias": "notice-service",
      "selectionTier": "primary",
      "coverage": "direct",
      "useWhen": "Any task about notice content, layout, or delivery logic.",
      "pathScope": ["templates/**", "src/delivery/**"]
    },
    {
      "resourceId": "repository:example-gov/eligibility-events",
      "alias": "eligibility-contract",
      "selectionTier": "supporting",
      "coverage": "reference",
      "useWhen": "When a notice depends on the shape of an upstream determination event."
    }
  ],
  "referenceResources": [
    {
      "resourceId": "reference:plain-language-standard",
      "useWhen": "Reviewing proposed notice wording.",
      "relianceCheck": "Confirm the specific rule is inside its review window before citing it."
    }
  ],
  "taskGuidance": {
    "synthesisBelongsIn": "product-work/benefits-notices/docs",
    "notes": "Deliverables and research for BN go under the product area's docs lanes. This area has a registered variance: ideas graduate straight to docs/plans."
  },
  "provenance": { "source": "sandbox seed", "addedBy": "kit" },
  "validation": { "status": "validated", "validatedBy": "kit", "validatedAt": "$D" }
}
EOF

# ---- A reviewed sync manifest ------------------------------------------------
mkdir -p "$cf/records/sync-manifests/releases/benefits-notices"
cat > "$cf/records/sync-manifests/releases/benefits-notices/$D.json" <<EOF
{
  "productId": "product:benefits-notices",
  "version": "$D",
  "updatedAt": "$D",
  "reviewedBy": "Priya Anand (fictional)",
  "catalogReferences": [
    "repository:example-gov/bn-notice-service",
    "repository:example-gov/eligibility-events"
  ],
  "repositories": [
    {
      "id": "repository:example-gov/bn-notice-service",
      "url": "https://git.example.gov/example-gov/bn-notice-service",
      "checkoutDirectory": "bn-notice-service"
    },
    {
      "id": "repository:example-gov/eligibility-events",
      "url": "https://git.example.gov/example-gov/eligibility-events",
      "checkoutDirectory": "eligibility-events"
    }
  ]
}
EOF

# ---- A generated repo digest (normally produced by tools/generate-repo-digests.sh)
# Included so a reader can see the artifact that answers most repository questions
# without git. In a real workspace this file is tool output and never hand-written.
mkdir -p "$cf/records/generated/repo-digests"
cat > "$cf/records/generated/repo-digests/bn-notice-service.md" <<EOF
---
repo: bn-notice-service
generated_at: $D
do_not_rely_after: 2026-09-27
source_commit: 0000000
source_branch: main
last_commit_date: $D
remote: https://git.example.gov/example-gov/bn-notice-service
---

# bn-notice-service

## Purpose (from repo README)

Renders and delivers beneficiary notices from upstream determination events.

## Top-level layout

- \`README.md\`
- \`src/\`
- \`templates/\`
- \`tests/\`

## Freshness

Digest reflects the local checkout at commit \`0000000\` ($D). For anything deeper than
purpose and layout, inspect the checkout at \`\${AGENTIC_REPO_CHECKOUT_ROOT}/bn-notice-service/\` —
this digest is orientation, not a substitute for the source.

<!-- FICTIONAL SANDBOX: normally generated by tools/generate-repo-digests.sh. -->
EOF

# ---- A generated routing card -----------------------------------------------
"$support/tools/route-artifact.sh" --card >/dev/null

# ---- Skill: replace example-skill with the team's own ------------------------
skills="$support/skills"
rm -rf "$skills/example-skill"
mkdir -p "$skills/notice-change-brief"
cat > "$skills/notice-change-brief/SKILL.md" <<'EOF'
---
workflow_id: notice-change-brief
version: 1
status: enabled
owner: Benefits Notices
source_of_truth: true
portable_across_harnesses: true
description: Draft a change brief for a proposed edit to a beneficiary notice, grounded in the BN product context.
argument-hint: "[notice ID, e.g. BN-072, and the proposed change]"
---

# Notice Change Brief

Use this skill when someone proposes changing the content or layout of a BN notice and
needs a reviewable brief before the change ships.

## Bindings

| Binding | Meaning | Resolution |
|---|---|---|
| `${AGENTIC_SUPPORT_ROOT}` | The support tree | The loaded support tree |
| `${AGENTIC_PRODUCT_WORK_ROOT}` | Shared product work | Descriptor, when declared; else an explicit caller input |

## Triggers

- "draft a change brief for BN-###"
- "we want to reword the renewal notice"

## Required Context

1. The workspace root `AGENTS.md`.
2. `product-work/benefits-notices/AGENTS.md` and the `product:benefits-notices` profile.
3. The current template set for the affected notice ID.
4. `reference:plain-language-standard`, checked against its own review window.

## Procedure

1. Confirm the notice ID (BN-###) and summarize the proposed change in one sentence.
2. Identify who is affected and any upstream dependency — check the profile's
   `eligibility-contract` repository, which is `reference` coverage: BN consumes the
   event shape and does not change it.
3. Check the proposed wording against the plain-language standard. Cite the specific rule.
4. Draft the brief and route it:
   `"${AGENTIC_SUPPORT_ROOT}/tools/route-artifact.sh" --type plan --area benefits-notices`.
   This area carries a registered variance; the tool prints it.

## Guardrails

- Never invent determination logic. Notices reflect upstream rules; they do not set them.
- Never reconstruct current notice text from memory — read the template set.
- Never renumber or reuse a notice ID.
- No credentials, no client-identifying data, no beneficiary data in the brief.

## Output Shape

A markdown brief with: Summary, Affected notices, Upstream dependency, Change detail,
Plain-language impact (with the cited rule), Accessibility impact, Rollback.

## Failure Handling

- Notice ID unknown or ambiguous: stop and ask. Do not infer it from a filename.
- Template set unavailable: produce the brief with the content section explicitly marked
  unverified, and say which template set is needed.
- Plain-language standard past its review window: treat it as unavailable, note the gap,
  and flag the wording for human review rather than asserting compliance.

## Harness Interpretation

Codex, Claude, OpenCode, and other harnesses produce the same brief shape. This file is
the source of truth for the procedure; an adapter that disagrees or is stale loses.
EOF

cat > "$skills/skill-manifest.yaml" <<'EOF'
version: 1

# The discovery and availability authority. `skills/<id>/SKILL.md` is the source of truth
# for behavior; this file decides what exists and whether it is runnable. Add or remove an
# entry in the SAME change as its canonical skill — validation/check-workspace.sh fails on
# a mismatch in either direction.

source_of_truth: agentic-support/skills

skills:
  - id: workspace-setup
    path: workspace-setup/SKILL.md
    status: enabled
  - id: artifact-routing
    path: artifact-routing/SKILL.md
    status: enabled
  - id: repo-sync
    path: repo-sync/SKILL.md
    status: enabled
  - id: notice-change-brief
    path: notice-change-brief/SKILL.md
    status: enabled

targets:
  codex: ~/.agents/skills
  claude: ~/.claude/skills
  opencode: ~/.config/opencode/skills
EOF

# Drop the placeholder review date the kit ships for example-skill; nothing is paused here.

printf 'Seeded sandbox at: %s\n' "$ws"
